TheGiant_Courtyard  = "(The Giant) Courtyard"
TheGiant_Pap = "(The Giant) Pack a Punch"
TheGiant_MonkeyBombs = "(The Giant) Monkey Bombs"
TheGiant_Quarter_Weapons = "(The Giant) Quarter Weapons"
TheGiant_Half_Weapons = "(The Giant) Half Weapons"

Castle_Gondola = "(Castle) Gondola"
Castle_MainEE = "(Castle) Main Easter Egg"
Castle_Upgraded = "(Castle) Upgraded Weapons"
Castle_BossFight = "(Castle) Boss Fight"
Castle_Quarter_Weapons = "(Castle) Quarter Weapons"
Castle_Half_Weapons = "(Castle) Half Weapons"

Shadows_Alleyway = "(Shadows of Evil) Alleyway"
Shadows_Widows = "(Shadows of Evil) Widows Wine Required"
Shadows_RayGun = "(Shadows of Evil) Ray Gun Required"
Shadows_Arnies = "(Shadows of Evil) Li'l Arnies Required"
Shadows_Upgraded = "(Shadows of Evil) Upgraded Weapons"
Shadows_MainEE = "(Shadows of Evil) Main Easter Egg"
Shadows_Quarter_Weapons = "(Shadows of Evil) Quarter Weapons"
Shadows_Half_Weapons = "(Shadows of Evil) Half Weapons"

Zetsubou_Beach = "(Zetsubou No Shima) Beach"
Zetsubou_Upgraded = "(Zetsubou No Shima) Upgraded Weapons"
Zetsubou_MainEE = "(Zetsubou No Shima) Main Easter Egg"
Zetsubou_Quarter_Weapons = "(Zetsubou No Shima) Quarter Weapons"
Zetsubou_Half_Weapons = "(Zetsubou No Shima) Half Weapons"

Gorod_Trenches = "(Gorod Krovi) Trenches"
Gorod_Bunker = "(Gorod Krovi) Bunker"
Gorod_Shield = "(Gorod Krovi) Shield Required"
Gorod_Upgraded = "(Gorod Krovi) Upgraded Weapons"
Gorod_MonkeyBombs = "(Gorod Krovi) Monkey Bombs Required"
Gorod_MainEE = "(Gorod Krovi) Main Easter Egg"
Gorod_Quarter_Weapons = "(Gorod Krovi) Quarter Weapons"
Gorod_Half_Weapons = "(Gorod Krovi) Half Weapons"

Revelations_House = "(Revelations) House"
Revelations_MainEE = "(Revelations) Main Easter Egg"
Revelations_Upgraded = "(Revelations) Upgraded Weapons"
Revelations_Apothicon_Upgrade = "(Revelations) Apothicon Upgrade"
Revelations_Arnies_Upgrade = "(Revelations) Arnies Upgrade"
Revelations_Quarter_Weapons = "(Revelations) Quarter Weapons"
Revelations_Half_Weapons = "(Revelations) Half Weapons"
